### ISSUE TITLE
Build failing during "Build Codeplugs" step (i.e. after dependencies are installed).

### ISSUE THREAD

**Issue by MaxBMitchell** [mycodeplug/example-codeplug#15] opened 2022-01-31 02:45 UTC
I am experiencing a failure when the action is attempting to run.  The log archive is attached for reference.  I don't know how to interpret all the info, but it seems there is an issue highlighted in the 7_Build_Codeplugs.txt log.  The process stops after observing this error.

After cloning, the only edit I made was to the following file, in which I modified the radio name.  I then commit and pushed as indicated in the walkthrough.
\mduv380-codeplug\input\default\example-md-uv380.json

2022-01-31T01:52:39.8716197Z json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 46 column 1 (char 825)

I don't see a lack of double quotes in either of the json files: 
\mduv380-codeplug\input\default\example-md-uv380.json
\mduv380-codeplug\input\default\scanlists.json

[6_Install dependencies.txt](https://github.com/mycodeplug/example-codeplug/files/7967578/6_Install.dependencies.txt)
[7_Build Codeplugs.txt](https://github.com/mycodeplug/example-codeplug/files/7967579/7_Build.Codeplugs.txt)
[16_Post Run actionscheckout@v2.txt](https://github.com/mycodeplug/example-codeplug/files/7967580/16_Post.Run.actionscheckout%40v2.txt)
[17_Complete job.txt](https://github.com/mycodeplug/example-codeplug/files/7967581/17_Complete.job.txt)
[1_Set up job.txt](https://github.com/mycodeplug/example-codeplug/files/7967582/1_Set.up.job.txt)
[2_Run actionscheckout@v2.txt](https://github.com/mycodeplug/example-codeplug/files/7967583/2_Run.actionscheckout%40v2.txt)
[3_Set up Python.txt](https://github.com/mycodeplug/example-codeplug/files/7967584/3_Set.up.Python.txt)
[4_Get current time.txt](https://github.com/mycodeplug/example-codeplug/files/7967585/4_Get.current.time.txt)
[5_Cache .cache.txt](https://github.com/mycodeplug/example-codeplug/files/7967586/5_Cache.cache.txt)

**Comment by masenf** [comment] 2022-01-31 03:09
Looks like the problem is in the data returned by Repeaterbook rather than anything on your end.

I'll see if I can determine the issue and then I'll report it to Garrett, the admin of repeaterbook.

Thanks for reporting this issue.

**Comment by masenf** [comment] 2022-01-31 04:04
I have confirmed that the issue is a formatting problem with the Repeaterbook API response and dispatched an email to the admin team over there. I'll keep this issue updated with any response that I get back.

To workaround the issue in the meantime, you may disable the "proximity csv" feature to avoid repeaterbook and skip generating channels and zones for analog repeaters.

**Comment by MaxBMitchell** [comment] 2022-01-31 04:39
Thanks for the response/suggestion.  The build works after removing all entries in prox.csv.

**Comment by masenf** [comment] 2022-01-31 04:56
20:33 PST Repeaterbook admin acknowledges that a comma was removed. I observe the issue to be resolved in this run: https://github.com/mycodeplug/example-codeplug/runs/5001385518

Thanks again for reporting and using dzcb. Please report any other problems you may find.

**Closed as completed by masenf** 2022-01-31 04:56 UTC
